_target_: src.models.image_classifiers.ImageConvClassifier

loss_name: crossentropy

image_dim: [40, 40]
n_classes: 2

convnet_config:
  - default_activation: ""
  - default_kernel: 3
  - default_padding: "same"
  - conv_layers:
    - {"type": "conv"}
    - {"type": "conv"}
    - {"type": "conv"}
  - dense_layers: []

defaults:
  - _self_
  - optimizer: fast.yaml
  - scheduler: cyclicwithwarmup.yaml
