# Reference taggers

- name: dense_Rodem_default
  path: /srv/beegfs/scratch/users/r/rothenf3/projects/MasterFranck/experiments/initial_testing/generalization/taggers/supervised_Rodem_default
  score_name: output
  label: dense default trained on Rodem
  plot_kwargs:
    linestyle: solid
    color: black

- name: dense_TopTag_default
  path: /srv/beegfs/scratch/users/r/rothenf3/projects/MasterFranck/experiments/initial_testing/generalization/taggers/supervised_TopTag_default
  score_name: output
  label: dense default trained on TopTag
  plot_kwargs:
    linestyle: solid
    color: blue

- name: dense_JetNet_default
  path: /srv/beegfs/scratch/users/r/rothenf3/projects/MasterFranck/experiments/initial_testing/generalization/taggers/supervised_JetNet_default
  score_name: output
  label: dense default trained on JetNet
  plot_kwargs:
    linestyle: solid
    color: red


# Taggers to compare

# IRM mass
- name: dense_Rodem_IRM_mass
  path: /srv/beegfs/scratch/users/r/rothenf3/projects/MasterFranck/experiments/initial_testing/generalization/taggers/supervised_Rodem_IRM_mass
  label: dense IRM mass trained on Rodem
  score_name: output
  plot_kwargs:
    linestyle: solid
    color: green

# # SAM taggers
# - name: dense_Rodem_SAM
#   path: /srv/beegfs/scratch/users/r/rothenf3/projects/MasterFranck/experiments/taggers/supervised_Rodem_SAM
#   label: dense SAM trained on Rodem
#   score_name: output
#   plot_kwargs:
#     linestyle: solid
#     color: green

# - name: dense_TopTag_SAM
#   path: /srv/beegfs/scratch/users/r/rothenf3/projects/MasterFranck/experiments/taggers/supervised_TopTag_SAM
#   label: dense SAM trained on TopTag
#   score_name: output
#   plot_kwargs:
#     linestyle: solid
#     color: orange

# - name: dense_JetNet_SAM
#   path: /srv/beegfs/scratch/users/r/rothenf3/projects/MasterFranck/experiments/taggers/supervised_JetNet_SAM
#   label: dense SAM trained on JetNet
#   score_name: output
#   plot_kwargs:
#     linestyle: solid
#     color: purple

# # Adversarial FGSM taggers
# - name: dense_Rodem_adversarial_FGSM
#   path: /srv/beegfs/scratch/users/r/rothenf3/projects/MasterFranck/experiments/taggers/supervised_Rodem_adversarial_FGSM
#   label: dense Adversarial FGSM trained on Rodem
#   score_name: output
#   plot_kwargs:
#     linestyle: solid
#     color: red
