
# tagger_dir: &tagger_dir "/home/users/r/rothenf3/workspace/Jettagging/jettagging/jobs/taggers"

- name: dense_test
  path: /home/users/r/rothenf3/workspace/Jettagging/jettagging/jobs/taggers/supervised
  score_name: output
  label: dense trained on Rodem
  plot_kwargs:
    linestyle: solid
    color: black

# - name: dense_jetnet_test
#   path: /home/users/r/rothenf3/workspace/Jettagging/jettagging/jobs/taggers/supervised_jetnet
#   score_name: output
#   label: dense trained on Jetnet
#   plot_kwargs:
#     linestyle: solid
#     color: blue

- name: dense_test_adversarial_FGSM
  path: /home/users/r/rothenf3/workspace/Jettagging/jettagging/jobs/taggers/supervised_adversarial_FGSM
  label: dense Adversarial FGSM
  score_name: output
  plot_kwargs:
    linestyle: solid
    color: red

- name: dense_test_IRM_mass_2023-12-11-11-19-55-248545
  path: /home/users/r/rothenf3/workspace/Jettagging/jettagging/jobs/taggers/supervised_IRM_mass
  label: dense IRM mass
  score_name: output
  plot_kwargs:
    linestyle: solid
    color: green

# - name: dense_jetnet_test_adversarial_RP
#   path: /home/users/r/rothenf3/workspace/Jettagging/jettagging/jobs/taggers/supervised_jetnet_RP
#   label: dense unsupervised RP
#   score_name: output
#   plot_kwargs:
#     linestyle: solid
#     color: green

# - name: dense_jetnet_test_adversarial_JP
#   path: /home/users/r/rothenf3/workspace/Jettagging/jettagging/jobs/taggers/supervised_jetnet_JP
#   label: dense unsupervised JP
#   score_name: output
#   plot_kwargs:
#     linestyle: solid
#     color: orange

# - name: dense_jetnet_test_adversarial_FGSMRP
#   path: /home/users/r/rothenf3/workspace/Jettagging/jettagging/jobs/taggers/supervised_jetnet_FGSMRP
#   label: dense unsupervised FGSMRP
#   score_name: output
#   plot_kwargs:
#     linestyle: solid
#     color: brown
