# output dir will be created by hydra
data_dir: /srv/beegfs/scratch/groups/rodem/anomalous_jets/virtual_data
#output_dir: /srv/beegfs/scratch/groups/rodem/anomalous_jets/taggers
output_dir: /home/users/r/rothenf3/workspace/Jettagging/jettagging/jobs/taggers

# Interpolated
root_dir: ${oc.env:PROJECT_ROOT}
full_path: ${paths.output_dir}/${project_name}/${network_name}
