model_checkpoint:
  _target_: pytorch_lightning.callbacks.ModelCheckpoint
  dirpath: ${paths.full_path}/checkpoints
  filename: best_{epoch:03d}
  monitor: valid/total_loss
  mode: min
  save_last: True
  auto_insert_metric_name: False

model_summary:
  _target_: pytorch_lightning.callbacks.RichModelSummary
  max_depth: 2

early_stopping:
  _target_: pytorch_lightning.callbacks.EarlyStopping
  monitor: valid/total_loss
  mode: min
  patience: 50

lr_monitor:
  _target_: pytorch_lightning.callbacks.LearningRateMonitor
  logging_interval: step
