# @package _global_

defaults:
  - hydra: default.yaml
  - paths: default.yaml
  - _self_

get_best: true

datamodule:
  _target_: src.datamodules.iterable_lightning.PointCloudDataModule
  data_conf:
    path: Null
    datasets: 
      c0: QCD_jj_pt_450_1200
      c1: ttbar_allhad_pt_450_1200
    iterator:
      _target_: src.datamodules.loading.JetClassIterator
      processes: 
        QCD: ["ZJets"]
        ttbar: ["TTBar_", "TTBarLep"]
      _partial_: True
      n_load: 10
    dataset_type: JetClass
    n_csts: 10
    n_steps: 3_000_000
    n_jets: 50_000
    coordinates:
      edge: []
      node:
      - del_eta
      - del_phi
      - log_pt
      high:
      - log_pt
      - log_mass
    incl_substruc: False
    del_r_edges: 0
  loader_kwargs:
    pin_memory: true
    batch_size: 128
    num_workers: 4
    drop_last: True



adversarial_export: False

project_name: supervised
network_name: transformer_multiclass
