# @package _global_

defaults:
  - taggers: export.yaml
  - data_confs: evaluated_on.yaml 
  - hydra: default.yaml
  - paths: default.yaml
  - _self_

get_best: true

# If set to true, will ignore above taggers and only export the single tagger specified below
export_single_tagger: false 
tagger_name: Null
tagger_path: Null

export_train: false

adversarial_export: false
SWA_export: false # Requires to have been trained with SWA
SWAG_export: false # Requires to have been trained with SWA

project_name: WhatIsMyPurpose
network_name: WhatIsMyPurpose
