_target_: src.datamodules.JIxPCmodule.JIxPCmodule

val_frac: 0.1
data_conf:
  path: ${paths.data_dir}
  datasets:
    c0: QCD_jj_pt_450_1200
  n_jets: 2_000_000
  n_csts: 64
  coordinates:
    edge:
    - del_R
    - log_kt
    - z
    - log_m
    - psi
    node:
    - del_eta
    - del_phi
    - log_pt
    high:
    - pt
    - mass
  image_params:
    bins: 40
    phi_bounds: [-1, 1]
    eta_bounds: [-1, 1]
    do_naive_const_preprocessing: 1
    image_transform:
      - "pixel_pow 0.5"
      - "sum_1_norm"
      - "gaussian_smearing 1"
      - "scale 100"
    image_transform2:
      - "sum_1_norm"
  min_n_csts: 1
  leading: True
  recalculate_jet_from_pc: False
  incl_substruc: False
  del_r_edges: 9999
  boost_mopt: 0
  augmentation_list: none
  augmentation_list_image: same
  augmentation_prob: 0
  do_plots: True

loader_kwargs:
  pin_memory: true
  batch_size: 32
  num_workers: 16
  drop_last: True
