mattstools:
  _target_: franckstools.franckstools.schedulers.WarmupToConstantSwag
  _partial_: true
  num_steps: 100
  swa_recording_lr_factor: 1.2
lightning:
  monitor: valid/total_loss
  interval: step
  frequency: 1


